# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['d:\\ishand folder\\cheating app'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'relay_client',
        'optimized_capture',
        'websocket',
        'websocket._core',
        'websocket._handshake',
        'websocket._http',
        'websocket._logging',
        'websocket._socket',
        'websocket._ssl_compat',
        'websocket._url',
        'websocket._utils',
        'cryptography',
        'cryptography.fernet',
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        'requests',
        'urllib3',
        'certifi',
        'charset_normalizer',
        'idna',
        'pyautogui',
        'pystray',
        'keyboard',
        'psutil',
        'win32gui',
        'win32con',
        'win32api',
        'win32clipboard',
        'pywin32'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='IgniteRemote',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None
)
